import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "@/app/thirdweb";
import { chain } from "./chain"; 

const clientId = process.env.NEXT_PUBLIC_CLIENT_ID as string;
const inter =Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider> 
          {children} 
        </ThirdwebProvider>
        
      </body>
    </html>
  );
}
